# parameters
# this should match what's in daikin_ekhhe_const.h on the cpp side
A_LOW_WAT_T_PROBE       = "low_water_temp_probe"
B_UP_WAT_T_PROBE        = "upper_water_temp_probe"
C_DEFROST_T_PROBE       = "defrost_temp_probe"
D_SUPPLY_AIR_T_PROBE    = "supply_air_temp_probe"
E_EVA_INLET_T_PROBE     = "evaporator_inlet_gas_temp_probe"
F_EVA_OUTLET_T_PROBE    = "evaporator_outlet_gas_temp_probe"
G_COMP_GAS_T_PROBE      = "compressor_discharge_gas_temp_probe"
H_SOLAR_T_PROBE         = "solar_collector_temp_probe"
I_EEV_STEP              = "eev_opening_step"
J_POWER_FW_VERSION      = "power_board_firmware_version"
L_UI_FW_VERSION         = "ui_firmware_version"

DIG1_CONFIG             = "dig1_config"
DIG2_CONFIG             = "dig2_config"
DIG3_CONFIG             = "dig3_config"

POWER_STATUS            = "power_status"
OPERATIONAL_MODE        = "operational_mode"
CURRENT_TIME            = "current_time"
AUTO_T_TEMPERATURE      = "auto_target_temperature"
ECO_T_TEMPERATURE       = "eco_target_temperature"
BOOST_T_TEMPERATURE     = "boost_target_temperature"
ELECTRIC_T_TEMPERATURE  = "electric_target_temperature"

P1_LOW_WAT_PROBE_HYST   = "low_water_hp_hysteris"
P2_HEAT_ON_DELAY        = "elec_heater_switch_on_delay"
P3_ANTL_SET_T           = "antilegionella_setpoint_temp"
P4_ANTL_DURATION        = "antilegionella_duration"
P5_DEFROST_MODE         = "defrosting_mode"
P6_EHEATER_DEFROSTING   = "elec_heater_during_defrosting"
P7_DEFROST_CYCLE_DELAY  = "defrosting_cycle_delay"
P8_DEFR_START_THRES     = "defrosting_start_temp_threshold"
P9_DEFR_STOP_THRES      = "defrosting_stop_temp_threshold"
P10_DEFR_MAX_DURATION   = "max_defrosting_duration"

P11_DISP_WAT_T_PROBE    = "display_water_probe_temp"
P12_EXT_PUMP_MODE       = "external_pump_mode"
P13_HW_CIRC_PUMP_MODE   = "hw_circ_pump_mode"
P14_EVA_BLOWER_TYPE     = "evaporator_blower_type"
P15_SAFETY_SW_TYPE      = "safety_flow_switch_type"
P16_SOLAR_MODE_INT      = "solar_mode_integration"
P17_HP_START_DELAY_DIG1 = "dig1_hp_start_delay"
P18_LOW_WAT_T_DIG1      = "dig1_low_water_temp_threshold"
P19_LOW_WAT_T_HYST      = "low_wat_probe_solar_hysteresis"
P20_SOL_DRAIN_THRES     = "solar_drain_temp_threshold"

P21_LOW_WAT_T_HP_STOP   = "low_water_hp_pv_mode_threshold"
P22_UP_WAT_T_EH_STOP    = "upper_water_eh_pv_mode_threshold"
P23_PV_MODE_INT         = "pv_mode_integration"
P24_OFF_PEAK_MODE       = "off_peak_working_mode"
P25_UP_WAT_T_OFFSET     = "upper_water_temp_probe_offset"
P26_LOW_WAT_T_OFFSET    = "lower_water_temp_probe_offset"
P27_INLET_T_OFFSET      = "air_inlet_temp_probe_offset"
P28_DEFR_T_OFFSET       = "defrost_temp_probe_offset"
P29_ANTL_START_HR       = "antilegionella_start_hour"
P30_UP_WAT_T_EH_HYST    = "upper_water_hysteresis_eh"

P31_HP_PERIOD_AUTO      = "hp_period_auto_mode_calc"
P32_EH_AUTO_TRES        = "eh_auto_mode_temp_threshold"
P33_EEV_CONTROL         = "eev_control"
P34_EEV_SH_PERIOD       = "eev_superheating_calc_period"
P35_EEV_SH_SETPOINT     = "eev_control_superheating_setpoint"
P36_EEV_DSH_SETPOINT    = "eev_control_desuperheating_setpoint"
P37_EEV_STEP_DEFR       = "defrosting_mode_eev_step"
P38_EEV_MIN_STEP_AUTO   = "auto_mode_min_eev_step"
P39_EEV_MODE            = "eev_control_mode"
P40_EEV_INIT_STEP       = "eev_step_opening_initial"

P41_AKP1_THRES          = "eev_kp1_gain_akp1_temp_threshold"
P42_AKP2_THRES          = "eev_kp2_gain_akp2_temp_threshold"
P43_AKP3_THRES          = "eev_kp3_gain_akp3_temp_threshold"
P44_EEV_KP1_GAIN        = "eev_kp1_gain"
P45_EEV_KP2_GAIN        = "eev_kp2_gain"
P46_EEV_KP3_GAIN        = "eev_kp3_gain"
P47_MAX_INLET_T_HP      = "max_inlet_temp_hp_working"
P48_MIN_INLET_T_HP      = "min_inlet_temp_hp_working"
P49_EVA_INLET_THRES     = "evaporator_inlet_temp_threshold_blower"
P50_ANTIFREEZE_SET      = "antifreeze_low_water_temp_setpoint"

P51_EVA_HIGH_SET        = "evaporator_blower_high_speed_set"
P52_EVA_LOW_SET         = "evaporator_blower_low_speed_set"